### PR TITLE
[socket.algo.async.connect] Add missing whitespace at end of sentence.

### PR DESCRIPTION
**Pull request by chriskohlhoff**

### CODE REVIEW

**Comment by jwakely** [comment]
Should there be a new paragraph before `ec` instead? That's what paragrap 8 on the next page does, and looks correct.

**Comment by jwakely** [comment]
I'll also italicise the "unspecified" arguments to the `s.async_connect` calls.

**Comment by chriskohlhoff** [comment]
> Should there be a new paragraph before ec instead? That's what paragrap 8 on the next page does, and looks correct.

Yes, you're correct. It should not be part of the itemised list.

**Comment by jwakely** [comment]
Fixed by 7bd7775fd63f6a0f0c7e30a67e8a8f026b61def8 instead.

**Pull request closed without merging**
